### ISSUE TITLE
could not find function 'crop'

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-dbscan-clusterer#2]
Getting it to run remotely (v0.0.4), but returns with below using the `test_req.json`. Any ideas @HughSt? Is that a function you're writing, or should be included from a lib?

```json
{
    "function_status": "error",
    "result": "Error in crop(parcel_lines, structure_points): could not find function \"crop\"\n"
}

```

**Comment by HughSt** [comment]
Thanks - needed the raster package loaded. My fault. Fixed and pushed, but haven't deployed.

**Comment by onlyjsmith** [comment]
Related to comment on your commit, I just located the list of packages in `rocker/geospatial` Docker image. Think is useful reference to keep handy.

https://github.com/rocker-org/geospatial
