### ISSUE TITLE
double-nested `result`

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-dbscan-clusterer#8]
We're wrapping the response in `result` twice, for no extra value! It's a different shape object to the returns from our other functions, so can be confusing for both UI builders and API users.

We do it in `function.R` and in `index.R`. Can remove it from `function.R`, and leave it in our more standard-ish handler code in `index.R`

```js
...
result: {
  result: {
...

```

Changing this, we'll also need to update the UI

**Comment by onlyjsmith** [comment]
Confirmed still the behaviour

**Comment by HughSt** [comment]
Yes I think remove from `function.R`. Also, I think our convention (and in the templates) has been to use `main.R` not `index.R`.

**Comment by onlyjsmith** [comment]
Are the Reveal team the only ones using this function? And I think they're not really using it much at the moment. Maybe we should fix asap?

**Comment by onlyjsmith** [comment]
@HughSt we've got a fix ready on the `use-template` branch see #9

**Comment by HughSt** [comment]
Great - I think the only change will be to the shiny UI that uses this function, so just need to coordinate

**Comment by onlyjsmith** [comment]
Can you point us to the right repo for the UI?
